name: in-context-learning
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.2.0
  - torchvision=0.17.0
  - torchaudio=2.2.0
  - pip
  - pip:
      - jupyter==1.0.0
      - matplotlib==3.8.4
      - numpy==1.26.4
      - pandas==2.2.2
      - quinine==0.3.0
      - scikit-learn==1.4.2
      - seaborn==0.13.2
      - tqdm==4.66.4
      - transformers==4.40.0
      - wandb==0.17.0
      - xgboost==2.1.0
      - protobuf==4.25.3
